
message(STATUS "Test enabled")
find_package(GTest REQUIRED)
if(VCPKG_TOOLCHAIN)
    # vcpkg provides GTest via config-mode targets (GTest::gtest / GTest::gtest_main).
    # Alias them to the bare names expected by all backend test CMakeLists files.
    if(NOT TARGET gtest AND TARGET GTest::gtest)
        add_library(gtest ALIAS GTest::gtest)
    endif()
    if(NOT TARGET gtest_main AND TARGET GTest::gtest_main)
        add_library(gtest_main ALIAS GTest::gtest_main)
    endif()
endif()
enable_testing()
# Add test directories
if(DEFAULT_BACKEND STREQUAL "LIBTENSORFLOW" )
    add_subdirectory(backends/libtensorflow/test)
elseif(DEFAULT_BACKEND STREQUAL "LIBTORCH" )
    message(STATUS "Libtorch test enabled")
    add_subdirectory(backends/libtorch/test)
elseif(DEFAULT_BACKEND STREQUAL "ONNX_RUNTIME")    
    add_subdirectory(backends/onnx-runtime/test)
elseif (DEFAULT_BACKEND STREQUAL "OPENCV_DNN")
    add_subdirectory(backends/opencv-dnn/test)
elseif(DEFAULT_BACKEND STREQUAL "TENSORRT")    
    add_subdirectory(backends/tensorrt/test)
elseif(DEFAULT_BACKEND STREQUAL "OPENVINO")
    add_subdirectory(backends/openvino/test)
elseif(DEFAULT_BACKEND STREQUAL "GGML")
    add_subdirectory(backends/ggml/test)
elseif(DEFAULT_BACKEND STREQUAL "TVM")
    add_subdirectory(backends/tvm/test)
elseif(DEFAULT_BACKEND STREQUAL "MIGRAPHX")
    add_subdirectory(backends/migraphx/test)
endif()    
